### ISSUE TITLE
Question:  Why would the default page (index.html) be blank

### ISSUE THREAD

**Issue by javadba** [vega/vega-editor#108]
I am new to npm / node.js and working through things here: including using a local npm directory so as not to require sudo and also updating the version of vega to the one expected by the vega-editor.

Now the `npm link` in vega and vega-lite work properly as does the `npm run vendor -- -l vega-lite -l vega` from vega-editor root.

After starting the SimpleHTTPServer and accessing the default index.html:

Serving HTTP on 0.0.0.0 port 8005 ...
127.0.0.1 - - [14/May/2017 10:15:42] "GET /vendor/topojson.js HTTP/1.1" 200 -
127.0.0.1 - - [14/May/2017 10:15:42] "GET /vendor/d3.min.js HTTP/1.1" 200 -
127.0.0.1 - - [14/May/2017 10:15:42] "GET /vendor/d3.geo.projection.min.js HTTP/1.1" 200 -
127.0.0.1 - - [14/May/2017 10:15:42] "GET /vendor/d3.layout.cloud.js HTTP/1.1" 200 -
127.0.0.1 - - [14/May/2017 10:15:42] "GET /vendor/ace/ace.js HTTP/1.1" 200 -
127.0.0.1 - - [14/May/2017 10:15:42] "GET /vendor/vega-embed.js HTTP/1.1" 200 -
127.0.0.1 - - [14/May/2017 10:15:42] "GET /vendor/json3-compactstringify.js HTTP/1.1" 200 -
127.0.0.1 - - [14/May/2017 10:15:42] "GET /app/vl-specs.js HTTP/1.1" 200 -

So we do not have any 404's : that is good .  However we also do not see anything displayed on the browser: a blank page.     When doing "show source" it does show the contents of 'index.html'. 

So what am I missing?

**Comment by domoritz** [comment]
If you are using Vega 3 or Vega-Lite 2, please use https://github.com/vega/vega-editor/tree/dom/vg3. Does that fix the problems?

**Comment by javadba** [comment]
BINGO!   thank you!

**Comment by javadba** [comment]
Ah sorry not so fast.  I still needed to re-do the `npm link` . Now get some errors (and the blank screen)

Serving HTTP on 0.0.0.0 port 8006 ...
127.0.0.1 - - [14/May/2017 10:33:56] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [14/May/2017 10:33:56] "GET /vendor/ace/ace.js HTTP/1.1" 200 -
127.0.0.1 - - [14/May/2017 10:33:56] "GET /vendor/vega.js HTTP/1.1" 200 -
127.0.0.1 - - [14/May/2017 10:33:56] "GET /vendor/vega-lite.js HTTP/1.1" 200 -
127.0.0.1 - - [14/May/2017 10:33:56] "GET /vendor/json3-compactstringify.js HTTP/1.1" 200 -
127.0.0.1 - - [14/May/2017 10:33:56] "GET /app/vega-specs.js HTTP/1.1" 200 -
127.0.0.1 - - [14/May/2017 10:33:56] "GET /app/vl-specs.js HTTP/1.1" 200 -
127.0.0.1 - - [14/May/2017 10:33:56] code 404, message File not found
127.0.0.1 - - [14/May/2017 10:33:56] "GET /vendor/d3.min.js HTTP/1.1" 404 -
27.0.0.1 - - [14/May/2017 10:33:56] "GET /app/editor.js HTTP/1.1" 200 -
127.0.0.1 - - [14/May/2017 10:33:56] code 404, message File not found
127.0.0.1 - - [14/May/2017 10:33:56] "GET /vendor/d3.min.js HTTP/1.1" 404 -

**Comment by domoritz** [comment]
You need to rerun the vendor script.

**Comment by javadba** [comment]
Thx for the update. I re-ran the vendor script and also the npm link's but
still the rendering does not happen.

2017-05-14 11:58 GMT-07:00 Dominik Moritz <notifications@github.com>:

**Comment by domoritz** [comment]
We are working on a new react based editor. Closing this issue.
