### ISSUE TITLE
I don't arrive to convert spec from Vega Editor into my dev locally. Need help

### ISSUE THREAD

**Issue by guks88** [vega/vega-editor#111]
This is my spec: 

{
  "$schema": "https://vega.github.io/schema/vega/v3.0.json",
  "width": 1,
  "height": 1,
  "padding": "auto",
  "data": [
    {
      "name": "source",
      "values": [
        {"name": "Moyenne","vote": "white","nbr": 20},
        {"name": "Moyenne","vote": "yes","nbr": 40},
        {"name": "Moyenne","vote": "no","nbr": 40}
      ]
    },
    {
      "name": "summary",
      "source": "source",
      "transform": [
        {
          "type": "aggregate",
          "groupby": ["name","vote"],
          "summarize": {"nbr": ["sum"]}
        }
      ]
    },
    {
      "name": "stacked_scale",
      "source": "summary",
      "transform": [
        {
          "type": "aggregate",
          "summarize": [{"ops": ["sum"],"field": "sum_nbr"}],
          "groupby": ["name"]
        }
      ]
    },
    {
      "name": "layout",
      "source": "summary",
      "transform": [
        {
          "type": "aggregate",
          "summarize": [{"field": "name","ops": ["distinct"]}]
        }
      ]
    }
  ],
  "marks": [
    {
      "name": "root",
      "type": "group",
      "from": {"data": "layout"},
      "properties": {
        "update": {
          "width": {"field": "width"},
          "height": {"field": "height"}
        }
      },
      "marks": [
        {
          "name": "marks",
          "type": "rect",
          "from": {
            "data": "summary",
            "transform": [
              {
                "type": "stack",
                "groupby": ["name"],
                "field": "sum_nbr",
                "sortby": ["-vote"],
                "output": {
                  "start": "sum_nbr_start",
                  "end": "sum_nbr_end"
                },
                "offset": "normalize"
              }
            ]
          },
          "properties": {
            "update": {
              "x": {"scale": "x","field": "sum_nbr_start"},
              "x2": {"scale": "x","field": "sum_nbr_end"},
              "yc": {"scale": "y","field": "name"},
              "height": {"value": 50},
              "fill": {"scale": "color","field": "vote"},
              "stroke": {"scale": "colorStroke","field": "vote"},
              "strokeWidth": {"value": 2}
            }
          }
        }
      ],
      "scales": [
        {
          "name": "x",
          "type": "linear",
          "domain": [0,1],
          "rangeMin": 0,
          "rangeMax": 500,
          "round": true,
          "nice": true,
          "zero": true
        },
        {
          "name": "y",
          "type": "ordinal",
          "domain": {"data": "summary","field": "name","sort": true},
          "padding": 1
        },
        {
          "name": "color",
          "type": "ordinal",
          "domain": {"data": "summary","field": "vote","sort": true},
          "range": ["#FF0000","#FFFFFF","#008000"]
        },
        {
          "name": "colorStroke",
          "type": "ordinal",
          "domain": {"data": "source","field": "vote"},
          "range": ["#000000"]
        }
      ],
      "axes": [{"type": "y","scale": "y"}],
      "legends": [
        {
          "fill": "color",
          "title": "vote",
          "orient": "left",
          "properties": {
            "symbols": {
              "shape": {"value": "circle"},
              "strokeWidth": {"value": 1}
            }
          }
        }
      ]
    }
  ]
}

I don't arrive to convert it into vega v3... Or can someone help me to do a horizontal stacked bar with this vega v3 spec:

{
  "$schema": "https://vega.github.io/schema/vega/v3.0.json",
  "width": 500,
  "height": 200,
  "padding": 5,
  "data": [
    {
      "name": "table",
      "values": [
        {"x": 0,"y": 28,"c": "yes"},
        {"x": 0,"y": 12,"c": "white"},
        {"x": 0,"y": 60,"c": "no"},
        {"x": 1,"y": 28,"c": "yes"},
        {"x": 1,"y": 12,"c": "white"},
        {"x": 1,"y": 60,"c": "no"},
        {"x": 2,"y": 28,"c": "yes"},
        {"x": 2,"y": 12,"c": "white"},
        {"x": 2,"y": 60,"c": "no"},
        {"x": 3,"y": 28,"c": "yes"},
        {"x": 3,"y": 12,"c": "white"},
        {"x": 3,"y": 60,"c": "no"},
        {"x": 4,"y": 28,"c": "yes"},
        {"x": 4,"y": 12,"c": "white"},
        {"x": 4,"y": 60,"c": "no"},
        {"x": 5,"y": 28,"c": "yes"},
        {"x": 5,"y": 12,"c": "white"},
        {"x": 5,"y": 60,"c": "no"},
        {"x": 6,"y": 28,"c": "yes"},
        {"x": 6,"y": 12,"c": "white"},
        {"x": 6,"y": 60,"c": "no"},
        {"x": 7,"y": 28,"c": "yes"},
        {"x": 7,"y": 12,"c": "white"},
        {"x": 7,"y": 60,"c": "no"},
        {"x": 8,"y": 28,"c": "yes"},
        {"x": 8,"y": 12,"c": "white"},
        {"x": 8,"y": 60,"c": "no"},
        {"x": 9,"y": 28,"c": "yes"},
        {"x": 9,"y": 12,"c": "white"},
        {"x": 9,"y": 60,"c": "no"}
      ],
      "transform": [
        {
          "type": "stack",
          "groupby": ["x"],
          "sort": {"field": "c"},
          "field": "y"
        }
      ]
    }
  ],
  "scales": [
    {
      "name": "x",
      "type": "band",
      "range": "width",
      "domain": {"data": "table","field": "x"}
    },
    {
      "name": "y",
      "type": "linear",
      "range": "height",
      "nice": true,
      "zero": true,
      "domain": {"data": "table","field": "y1"}
    },
    {
      "name": "color",
      "type": "ordinal",
      "domain": {"data": "table","field": "c","sort": true},
      "range": ["#FF0000","#FFFFFF","#008000"]
    },
    {
      "name": "colorStroke",
      "type": "ordinal",
      "domain": {"data": "table","field": "c"},
      "range": ["#000000"]
    }
  ],
  "axes": [
    {"orient": "bottom","scale": "x"},
    {"orient": "left","scale": "y"}
  ],
  "marks": [
    {
      "type": "rect",
      "from": {"data": "table"},
      "encode": {
        "enter": {
          "x": {"scale": "x","field": "x"},
          "width": {"scale": "x","band": 1,"offset": -5},
          "y": {"scale": "y","field": "y0"},
          "y2": {"scale": "y","field": "y1"},
          "stroke": {"scale": "colorStroke","field": "c"},
          "strokeWidth": {"value": 0.5},
          "fill": {"scale": "color","field": "c"}
        },
        "update": {"fillOpacity": {"value": 1}},
        "hover": {"fillOpacity": {"value": 0.5}}
      }
    }
  ]
}

Thank you very much in advance.

**Comment by domoritz** [comment]
Please use the Dom/vg3 branch.
