### ISSUE TITLE
Editor size in Safari

### ISSUE THREAD

**Issue by arvind** [vega/vega-editor#160]
In Safari Version 10.0 (12602.1.50.0.10) on macOS Sierra 10.12 (16A323), the editor appears as follows (with only a 5px height):

<img width="951" alt="screenshot 2017-06-17 16 39 56" src="https://user-images.githubusercontent.com/42262/27256977-ae22b102-537b-11e7-80a9-13f67a12ee27.png">

**Comment by domoritz** [comment]
Probably a flexbox issue :-(. Thanks for the report.

**Comment by domoritz** [comment]
No idea why, but safari seems to not use "height: 100%" for the edtior.

**Comment by domoritz** [comment]
Firefox works as expected. Safari is the new IE.
