### ISSUE TITLE
ReferenceError: vg is not defined

### ISSUE THREAD

**Issue by churtado** [vega/vega-editor#169]
I'm using ubuntu 16.04

I followed the install instructions, first installed the dependencies, then ran npm start. I'm getting that error in the firefox debug console. Same in chrome. I'm happy to give more information if needed.

**Comment by domoritz** [comment]
Which branch are you using?

**Comment by churtado** [comment]
I'm using master. I actually got it working now by using the solution posted here:

https://groups.google.com/forum/?nomobile=true#!msg/d3-js/uc_Zmf8-dsQ/hk-Hi1RrBAAJ

**Comment by domoritz** [comment]
Master is outdated. If you want Vega 3, use dom/vg3. redux is a complete rewrite in react. 

I'm glad it works for you now.

**Comment by churtado** [comment]
Thanks, will do.
