### ISSUE TITLE
Document how editor can be used as a component

### ISSUE THREAD

**Issue by nyurik** [vega/vega-editor#194]
While editor as an "app" is great (love the new design!), it would be awesome to be able to re-use it in other apps.  I would love to drop-in this editor into an HTML element container, specifying `editorContainerElement` and `onSpecChange` handler.  I might also want to have my own set of app-specific examples, for both Vega & VegaLite. Lastly, it is important to allow the debugging functionality as part of the editor, so there may be a need to tie the vega rendering back to the editor.

The editor as a component should just do the JSON editing, whereas my code will do spec pre-processing and call Vega or VegaLite to draw.

**Comment by domoritz** [comment]
We make heavy use of monaco and the JSON schema. Yes, it the future, we may tie back some of the error reporting into the editor but right now you get exactly what we support by just using monaco + vega and vega-lite json schemas.
