### ISSUE TITLE
Error on npm install

### ISSUE THREAD

**Issue by jlove29** [vega/vega-editor#198]
Errors raised on npm install, beginning with:

vega-editor-redux/node_modules/vega/docs/vega-schema.json: No such file or directory
vega-editor-redux/node_modules/vega/docs/examples/*.vg.json: No such file or directory
vega-editor-redux/node_modules/vega/docs/_data/examples.json: No such file or directory

[npm-debug copy.txt](https://github.com/vega/vega-editor/files/1163679/npm-debug.copy.txt)

**Comment by domoritz** [comment]
I suspect that this works if you use yarn and run the vendor script. Yes, the development process needs to be simplified.
