### ISSUE TITLE
Post message with spec does not work

### ISSUE THREAD

**Issue by domoritz** [vega/vega-editor#21]
```js
window.postMessage({spec:{}, mode:"vega"}, "https://vega.github.io/vega-editor/")
```

Results in `Uncaught TypeError: e.match is not a function` in the ace editor.

**Comment by arvind** [comment]
The value of the `spec` property is expected to be a string.  `window.postMessage({spec:"{}", mode:"vega"}, "https://vega.github.io/vega-editor/")` correctly works for me.

**Comment by domoritz** [comment]
Duh. I love untyped languages.
