### ISSUE TITLE
Permission to reuse examples

### ISSUE THREAD

**Issue by eterna2** [vega/vega-editor#214]
Hi, 

I am building another `vega-editor` but with webcomponents instead. 

I am asking for permission to reuse your Vega and Vega-Lite examples for my eventual app?

I have also create a google cloud function to automatically render Vega or Vega-Lite spec into SVG, PNG, or HTML via lz-string compressed query string of the spec. My app will help generate this unique link which then can be used to share any Vega or Vega-Lite charts. 

I have just finish converting `monaco editor` as a webcomponent, and is going to extend it into a `vega-editor`. Here is a link to a demo a mocked-up [vega-editor](https://polymervis.github.io/monaco-editor/build/demo/)

This is an example of embedding a chart with my API service. You can click on the chart to view the HTML version.
[![Click to see chart](https://e2.fyi/api/vg?key=N4WAUABBBEAkDOBjAFgUwLYENoC4bIBcCAHeHAenIDdUBzTAOloEsDkBXAIweYHtykaLNTqZqAZgYAGBgCt4vAHbQANOCjQA7swAmbXBAAsUqWsj5UzWoQMAmE2Y3FMOnc0W0DAVjPqYOzAJsPABtPyhQcygNRUx0VANoIM4AGwTHaI0qTBT2VHgDMKjMiGBoREC6XgAnAE9EgEFVGDjedkUCOwAOAF8MktLyytoa+rxoACFm6Fb2zrwvLz7wkrKKgiq6xIBhadmOg0NxZeLMteHRxIARPfQ2g7wATgBGE4GIoY2RrfGAUVv7vMIF1Xv1Vp9NmMYAAxAFzbzHMFnCHfKHQADicIeEGejze73OX0u4wAEligV0AOw9FZQAC6Kxp5jpvnM0HgVliKQKoRWkQG0Fi8USBF4vBSBGYxFUtJg2VyCTwwHxmWgSkKso+qBoHR5MGqqEQBBwd3Y8FQvBo1Wm7GIAQ2iXt7HQ0BV4O1qF1iQNRpNbXNbU6Kg0tvtipgytdsoZxSZ9NZGiQOXyGuK-JKgri4egAA8k2kZacYARasRs5xMIodIWBTpeFh3AYyvbgsXMKl0jAAGbMVApavjdaQ11I-WV2jZ7R6ZA1jPOVzuTx4GRSHyy6DVe4DiAEap5Rlg9OqoXZ2r59LrusN5RK6AtkXtgvB6A9vvbmamg5umLMRDh3d5KOG7jtmaBWDYjJ+Cy4B+DMOYpryaYwDUvbYtAnC8EQ9bTOeiR5hUBYQG6wDIdUqFAtAaRdkGMC4eMZ4EQkRFQQmMBYNUADWepFGc64lmW3qGkG65dpuLq3veOBJI+CTfjAnqILwOjhkeGaehs1pKpq0S5k27KMXhuHPq+-aJEOqIjtpGhTvot50TA+HJtMFZVgYoJWTAUJlPZ0AMU5xm9qZ4z7J0cmqrUth6T5flPnKOR5AYUhxu8YUwKGlRNh5L7MCkKR6fKCXjPAGx9qkCXJQMqXQMglqoJppRZT2uX5fF2YGtWFUlJ1UCdcRfGltmGw5sJRbQApSkqdpY0dHVmVFqqOSci1Cpmeps2pRoFbmik7gqdABXlphoouht3Y5Xlt4HYkADE4h3VG81EaOIZ2hlWmPRoOZRQZ4yObF7KcjkIpihKUoMOZlzPi524yEsz06V5+lOfRRm0YDF3FiDkrEAwIXTLwXZduaQIALS2KdSSoMNUXo8D4rY7jn6hfDGhNSkADyziIKwUI8e8yIbMVjqBM6EAALwSzuWNStMV3LqdHxyzi3UlDG-Mq71UHgEyQA)](https://e2.fyi/api/vg?mode=html&key=N4WAUABBBEAkDOBjAFgUwLYENoC4bIBcCAHeHAenIDdUBzTAOloEsDkBXAIweYHtykaLNTqZqAZgYAGBgCt4vAHbQANOCjQA7swAmbXBAAsUqWsj5UzWoQMAmE2Y3FMOnc0W0DAVjPqYOzAJsPABtPyhQcygNRUx0VANoIM4AGwTHaI0qTBT2VHgDMKjMiGBoREC6XgAnAE9EgEFVGDjedkUCOwAOAF8MktLyytoa+rxoACFm6Fb2zrwvLz7wkrKKgiq6xIBhadmOg0NxZeLMteHRxIARPfQ2g7wATgBGE4GIoY2RrfGAUVv7vMIF1Xv1Vp9NmMYAAxAFzbzHMFnCHfKHQADicIeEGejze73OX0u4wAEligV0AOw9FZQAC6Kxp5jpvnM0HgVliKQKoRWkQG0Fi8USBF4vBSBGYxFUtJg2VyCTwwHxmWgSkKso+qBoHR5MGqqEQBBwd3Y8FQvBo1Wm7GIAQ2iXt7HQ0BV4O1qF1iQNRpNbXNbU6Kg0tvtipgytdsoZxSZ9NZGiQOXyGuK-JKgri4egAA8k2kZacYARasRs5xMIodIWBTpeFh3AYyvbgsXMKl0jAAGbMVApavjdaQ11I-WV2jZ7R6ZA1jPOVzuTx4GRSHyy6DVe4DiAEap5Rlg9OqoXZ2r59LrusN5RK6AtkXtgvB6A9vvbmamg5umLMRDh3d5KOG7jtmaBWDYjJ+Cy4B+DMOYpryaYwDUvbYtAnC8EQ9bTOeiR5hUBYQG6wDIdUqFAtAaRdkGMC4eMZ4EQkRFQQmMBYNUADWepFGc64lmW3qGkG65dpuLq3veOBJI+CTfjAnqILwOjhkeGaehs1pKpq0S5k27KMXhuHPq+-aJEOqIjtpGhTvot50TA+HJtMFZVgYoJWTAUJlPZ0AMU5xm9qZ4z7J0cmqrUth6T5flPnKOR5AYUhxu8YUwKGlRNh5L7MCkKR6fKCXjPAGx9qkCXJQMqXQMglqoJppRZT2uX5fF2YGtWFUlJ1UCdcRfGltmGw5sJRbQApSkqdpY0dHVmVFqqOSci1Cpmeps2pRoFbmik7gqdABXlphoouht3Y5Xlt4HYkADE4h3VG81EaOIZ2hlWmPRoOZRQZ4yObF7KcjkIpihKUoMOZlzPi524yEsz06V5+lOfRRm0YDF3FiDkrEAwIXTLwXZduaQIALS2KdSSoMNUXo8D4rY7jn6hfDGhNSkADyziIKwUI8e8yIbMVjqBM6EAALwSzuWNStMV3LqdHxyzi3UlDG-Mq71UHgEyQA)

**Comment by domoritz** [comment]
Hi @eterna2, we are thrilled to hear that you're building another editor. Feel free to use any examples that you find in the Vega and Vega-Lite repos. They are all under the same license as the code (BSD-3). 

Although it's not a requirement for using the examples, we would love if you added a link to the documentation in the app and acknowledge the source of the examples in the readme of your repo. this way there also won't be any confusion about where to post issues and sent PRs for improvements :-)

**Comment by domoritz** [comment]
Closing this as there are no actions remaining.
