### ISSUE TITLE
Installing veg-editor from master branch fails.

### ISSUE THREAD

**Issue by abhibasu** [vega/vega-editor#26]
The npm command to get dependencies is failing, please see details below.

# npm run vendor

> vega-editor@1.2.0 prevendor /usr/local/bin/vega-editor-master
> npm install

npm http GET https://registry.npmjs.org/d3-geo-projection
npm http GET https://registry.npmjs.org/d3-cloud
npm http GET https://registry.npmjs.org/vega
npm http GET https://registry.npmjs.org/vega-embed
npm http GET https://registry.npmjs.org/topojson
npm http GET https://registry.npmjs.org/d3
npm http GET https://registry.npmjs.org/vega-lite
npm http GET https://registry.npmjs.org/chokidar
npm http GET https://registry.npmjs.org/ace-builds
npm http GET https://registry.npmjs.org/vega-datasets
npm http 304 https://registry.npmjs.org/d3-geo-projection
npm http 304 https://registry.npmjs.org/vega
npm http 304 https://registry.npmjs.org/d3-cloud
npm http 304 https://registry.npmjs.org/vega-embed
npm http 304 https://registry.npmjs.org/topojson
npm http 304 https://registry.npmjs.org/chokidar
npm http 304 https://registry.npmjs.org/d3
npm http 404 https://registry.npmjs.org/ace-builds
npm http 304 https://registry.npmjs.org/vega-lite
npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:708:24)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-431.23.3.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /usr/local/bin/vega-editor-master
npm ERR! node -v v0.10.17
npm ERR! npm -v 1.3.8
npm ERR! type called_on_non_object
npm http 404 https://registry.npmjs.org/vega-datasets
npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (/usr/local/lib/node_modules/npm/lib/cache.js:708:24)
npm ERR!     at /usr/local/lib/node_modules/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/local/lib/node_modules/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/local/lib/node_modules/npm/node_modules/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 2.6.32-431.23.3.el6.x86_64
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /usr/local/bin/vega-editor-master
npm ERR! node -v v0.10.17
npm ERR! npm -v 1.3.8
npm ERR! type called_on_non_object
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /usr/local/bin/vega-editor-master/npm-debug.log
npm ERR! not ok code 0
npm ERR! weird error 1
npm ERR! not ok code 0

Thanks,

Abhi

**Comment by arvind** [comment]
Hi Abhi,

These are a very strange set of errors that I'm not able to reproduce. I
wonder if the errors are related to the fact that your npm version is quite
old, and we may be relying on features introduced in newer versions. You
might try re-running the command with a newer version of npm (I recommend
2.x, as others have experienced issues with 3.x).

-Arvind
-----
Arvind Satyanarayan <http://arvindsatya.com/>

**Comment by arvind** [comment]
Hi Abhi, if you're still experiencing issues, please post to the [vega-js google group](https://groups.google.com/forum/#!forum/vega-js). Thanks!
