### ISSUE TITLE
Use schema to enrich user experience?

### ISSUE THREAD

**Issue by bollwyvl** [vega/vega-editor#3]
New vega looks great, and the editor looks great. Congratulations!

I also love seeing d3 used for non-svg hacking: you've made a tool that is already in the language of a core user group, not some framework-heavy nest of $scope.

But focusing on the user: authoring JSON, even with ACE handling all your metacharacters, is _harsh_.

Now that you have a schema (yay!) it should be possible to hook it into ACE: on the [JSON-LD playground](http://json-ld.org/playground/) we've done [something similar](https://github.com/json-ld/json-ld.org/blob/master/playground/json-schema-lint.js) for CodeMirror.

Happy to help out if this is desirable!

**Comment by arvind** [comment]
Indeed, we have JSON schema validation hooked into ace forthcoming. We just didn't have it ready in time for release ;) Once it's in (and it uses the same two libraries as your CodeMirror link!), I'll update this issue and would love for PRs to improve its functionality. Thanks!

**Comment by bollwyvl** [comment]
Sounds great!

**Comment by domoritz** [comment]
Supported in the new editor.
