### ISSUE TITLE
crossfilter example: time of day distribution for is wrong

### ISSUE THREAD

**Issue by espinielli** [vega/vega-editor#34]
It looks line issue #2 resurfaced.

**Comment by Jerrythafast** [comment]
I can confirm this (timezone UTC+1). Tested with Vega 2.4.0.

**Comment by arvind** [comment]
Thanks all for the bug report. Looks like an older version of the crossfilter data was copied over when we created the vega-datasets repository. I've fixed it with vega/vega-datasets@1e70098, which should go live sometime next week.
