### ISSUE TITLE
YAML editing?

### ISSUE THREAD

**Issue by bollwyvl** [vega/vega-editor#4]
Continuing on the user focus in #3:

Perhaps enabling an alternate mode using YAML->JSON would make this experience more pleasant and productive. I am not suggesting YAML is the _best format_, or should become supported by vega, but I have found YAML to be the the _best editor_ for JSON-compatible datatypes.

I'd love to pitch in, if you would welcome this kind of change :monkey_face:.

> Somewhat off-topic: I'm also interested in integrating a vega livecoding experience against the IPython widget data model, similar to [this little experiment](https://github.com/bollwyvl/ipylivecoder). The widget really just brings the opinion that data is a Backbone `Model`, and that `update` is called. While datalib is amazing, it's really hard to beat the velocity of python data science development. This would be different than [vincent](https://github.com/wrobstory/vincent), instead treating the vega tree as another datum to be manipulated, and reactive to Things Changing on the backend. Would love feedback!

**Comment by domoritz** [comment]
See https://github.com/vega/vega-editor/issues/54
