### ISSUE TITLE
Add view for data

### ISSUE THREAD

**Issue by willium** [vega/vega-editor#45]
It would be nice to be able to see the data that's being used as the data-source for the visualizations in the editor, much in the way you can with [blocks](http://bl.ocks.org/mbostock/7441121). Maybe implementation could be similar to how you can see the vega spec from the vega-lite mode.

**Comment by arvind** [comment]
Yup, this will be available once we merge in @jhoffswell's work.

**Comment by willium** [comment]
I believe this was recently merged in! Great work.
