### ISSUE TITLE
Get shareable link for custom vega & vega-lite spec?

### ISSUE THREAD

**Issue by ZeningQu** [vega/vega-editor#47]
It would be nice if a user can share a custom visualization and its spec by copying & pasting its url (like [JSFiddle](https://jsfiddle.net/). Right now for all the examples we have `spec=[example_name]` in the url. For custom visualizations this can be `spec=[unique_spec_id]`.

**Comment by domoritz** [comment]
Yeah, we were thinking about gists as a possible storage option. Similar to blocks.

**Comment by Jerrythafast** [comment]
For the not-so-big specs you might get away with putting `base64` encoded data in `window.location.hash`. If it gets too long, you can also try compressing the spec (a quick Google search pops up some JavaScript LZW compression library) or stripping all the whitespace on store and doing auto-formatting on load.

**Comment by willium** [comment]
I'd like to implement the gists storage option @domoritz.

@Jerrythafast unfortunately that idea was recently shot-down (I like it a lot too). It was considered unreliable and confusing if sometimes you could right link and other times you couldn't, for instance)

Alternatively, we could build a system like JSFiddle with a save button and a simple key, value datastore.

**Comment by kanitw** [comment]
I believe @jheer have a prototype branch that investigate the gist idea.

**Comment by domoritz** [comment]
@jheer and @arvind were suggesting that we should not add too many features to the current editor as a rewrite seems imminent. 

Maybe instead of adding it to the editor, we should have something like gist for vega/ vega-lite and an export to that system from the editor.

**Comment by willium** [comment]
I was thinking more along the line of a hidden feature. https://vega.github.io/vega-editor/?mode=vega?gist=GIST_ID

**Comment by willium** [comment]
It seems like Jeff did start a branch with this https://github.com/vega/vega-editor/tree/jh-gists

**Comment by jheer** [comment]
@willium, Take a look at these
- https://github.com/vega/web-service
- https://github.com/vega/vega-gist

The first is a web-service that aids with GitHub OAuth. We already have an OAuth app for the Vega organization, and a web service running on Heroku. Also check out https://github.com/vega/web-service/blob/gh-pages/oauth/index.html

The second is a (currently empty) repo that is intended to house a stand-alone API for managing Vega Gists. I have some starter code for this which extends the branch you've found above. I can share with you; see me in person for more.

**Comment by domoritz** [comment]
PR for gists: https://github.com/vega/vega-editor/pull/138
