### ISSUE TITLE
"Parse" automatically swap to Vega-Lite if a Vega-Lite spec is parse in Vega mode.

### ISSUE THREAD

**Issue by kanitw** [vega/vega-editor#52]
(I don't know how many times I have clicked parse but forgot to change to Vega-Lite mode first)

**Comment by domoritz** [comment]
How do you know it's vega-lite?

**Comment by kanitw** [comment]
One possible predicate is If it validates vl schema but not vg schema.

**Comment by domoritz** [comment]
The new editor could parse the schema url using https://github.com/vega/schema/tree/parser.

**Comment by domoritz** [comment]
This works now.
