### ISSUE TITLE
Consider Hjson

### ISSUE THREAD

**Issue by domoritz** [vega/vega-editor#54]
See https://github.com/vega/vega/issues/571

**Comment by kanitw** [comment]
HJSON has many design flaws I don't like.  I don't think we should support it. 

The only thing that I think is useful from HJSON is commenting.  

Omitting braces, quotes make it impossible to copy a spec to a javascript file.

**Comment by domoritz** [comment]
Even with comments its impossible. I think there should be a hjson -> json button in the editor if we end up supporting hjson. Another option is yaml.

**Comment by kanitw** [comment]
Why is it impossible with comments?

**Comment by domoritz** [comment]
>Why is it impossible with comments?

How do you comment in json?

**Comment by arvind** [comment]
I'm hesitant to include more than JSON in the editor for a few reasons. Extensions to JSON that have been proposed (of which [HJSON](http://hjson.org) is just one of many, see also [JSON5](http://json5.org/)) are far from being widely adopted or standardized. If we adopt one of these solutions, we paint ourselves into a corner if it ends up diverging from however JSON proper evolves in the future. This isn't necessarily a big problem with the current state of the editor, but as the editor itself evolves (e.g., saving/loading from gists), supporting an "old" format opens us up to backward compatibility issues that are completely orthogonal to our core work.

Along this axis, YAML is better -- it's a standard and has seen broader adoption (though I'd argue at least an order of magnitude less than JSON). YAML support in the editor has also been previously requested (#4). I worry, however, about whether introducing it brings more problems than it solves, particularly in terms of understandability for first-time/novice users. For example, if we introduce YAML support in the editor, an extra step is needed to get the equivalent JSON. Of course a button could be provided, but it nevertheless adds more friction to the user experience. Similarly, with multiple formats supported, while we can ensure our documentation consistently uses the same format type (e.g., JSON), perhaps we'll see 3rd parties writing Vega tutorials with YAML code snippets. Now, users need to manually match YAML and JSON code snippets. The latter is a pain point I've experienced a lot with [ESLint](http://eslint.org/) which allows its configuration files to be specified as either YAML or JSON. Our Lyra ESLint config file is in YAML, the ESLint documentation provides JSON snippets, and tutorials on the web provide both. Mapping from one to another has been an unnecessary source of frustration for me.

**Comment by domoritz** [comment]
Thanks for the in depth response and the anecdote about YAML to configure ESLint.
