### ISSUE TITLE
Vega Tutorial specifications don't work in the Editor

### ISSUE THREAD

**Issue by kernc** [vega/vega-editor#88]
If any of the two current [Vega tutorials](https://vega.github.io/vega/tutorials/) specifications is copied into the live [Vega Editor](https://vega.github.io/vega-editor/), upon parsing, the visualization fails to render.

In case of first tutorial, bar-chart, the error in the console is:
> Error: Unrecognized scale type: band

In case of airports, the error is:
> Error: "geopoint" is not a valid transformation

What version of Vega is the editor running and what can one do to overcome these issues?

**Comment by kanitw** [comment]
Thanks for reporting.  Current the [online Vega editor](https://vega.github.io/vega-editor/) uses Vega v2.  

We have an *alpha* version of the new Vega-editor published online [here](https://vega.github.io/new-editor/) that uses Vega v3. That said, keep in mind that it's still in alpha so it might be a bit less stable.  

If you prefer the current (old) editor, we also have [this branch] that works with Vega v3.
