### ISSUE TITLE
exporting visualizations

### ISSUE THREAD

**Issue by jojo05** [vega/vega-editor#9]
It would be very useful to have a button next to the visualization so that it can be exported as a png or svg file.

Also, given that the json files are verbose I would focus on two user cases:
1) quick output: given a csv file with the table and a chart type, the editor does the right thing
2) detailed: similar to what you have but even more complete (e.g. the stocks chart should show the ticker, ...)

**Comment by jheer** [comment]
Thanks for the request! Image (png/svg) export was added in f7b7b4b3ab3b34f56f59e89d878d3f8fa3f91237.

Regarding "quick output", take a look at our [vega-lite](https://github.com/uwdata/vega-lite) sister project. Once that is mature enough for 1.0 release, we will consider adding vega-lite support to vega-editor.
