### ISSUE TITLE
Don't automatically format

### ISSUE THREAD

**Issue by domoritz** [vega/vega-editor#94]
https://github.com/vega/vega-editor/blob/master/lib/json3-compactstringify.js creates a much more compact json representation.

**Comment by mathisonian** [comment]
@kanitw - @tianyiii pushed code to fix this here, but it still behaves differently from the current editor. I'm kind of at a loss why 


old 
<img width="474" alt="screen shot 2017-05-18 at 3 38 00 pm" src="https://cloud.githubusercontent.com/assets/1074773/26226257/2eaa78ae-3be0-11e7-9dff-b1f499d1e485.png">

new 

<img width="702" alt="screen shot 2017-05-18 at 3 37 40 pm" src="https://cloud.githubusercontent.com/assets/1074773/26226254/29d09354-3be0-11e7-9a8d-f290b6f551d5.png">

code for the new one - https://github.com/vega/vega-editor/blob/redux/src/reducers/app/index.js#L84
code for old - https://github.com/vega/vega-editor/blob/master/app/editor.js#L168

**Comment by domoritz** [comment]
It's all correct. The difference is that we do not format the code when we load the json file for the first time. We just take the format as is. You see it when you hit `format` in the old editor. 

See
```
JSON3.stringify({
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A","b": 28}, {"a": "B","b": 55}, {"a": "C","b": 43},
      {"a": "D","b": 91}, {"a": "E","b": 81}, {"a": "F","b": 53},
      {"a": "G","b": 19}, {"a": "H","b": 87}, {"a": "I","b": 52}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative"}
  }
}
, null, 2, 60);
"{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A","b": 28},
      {"a": "B","b": 55},
      {"a": "C","b": 43},
      {"a": "D","b": 91},
      {"a": "E","b": 81},
      {"a": "F","b": 53},
      {"a": "G","b": 19},
      {"a": "H","b": 87},
      {"a": "I","b": 52}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a","type": "ordinal"},
    "y": {"field": "b","type": "quantitative"}
  }
}"
```

I think it would be nice to not reformat automatically when we first load a spec as the formatting is intentional in many cases.

**Comment by kanitw** [comment]
Yeah, our hand formatted VL specs usually have nicer format than the auto-format.

**Comment by domoritz** [comment]
I think I fixed this.
